### ISSUE TITLE
The 'predict' funtion in MLGL didn't work

### ISSUE THREAD

**Issue by XingfuXu** [modal-inria/MLGL#1]
Hello, I'm using the MLGL package to do some research. Recently,I found that the 'predict' function in the package didn't work. I didn't find an example of the 'predict' function in the package document. Can you help me find the reason why it didn't work or give me an example of how it can work. Many thanks. Below is my code.

``` r
library(MLGL)
X <- simuBlockGaussian(n = 50, nBlock = 12, 
                       sizeBlock = 5, rho = 0.7)
y <- drop(X[, c(2, 7, 12)] %*% c(2, 2, -1)) + rnorm(50, 0, 0.5)
# Build a MLGL forecast
m1 <- MLGL(X, y, loss = "ls")
predict(m1, s = "lambda.min", newx = X)  # It didn't work.
# or
m2 <- cv.MLGL(X, y, loss = "ls")
predict(m2, s = "lambda.min", newx = X)  # It didn't work.
```

**Comment by Quentin62** [comment]
Hi, s must be a vector of values of lambda. If NULL it uses the lambda values in object.
I will add an example in the documentation and some checks for the s parameter.

``` r
X <- simuBlockGaussian(n = 50, nBlock = 12,
                       sizeBlock = 5, rho = 0.7)
y <- drop(X[, c(2, 7, 12)] %*% c(2, 2, -1)) + rnorm(50, 0, 0.5)


m1 <- MLGL(X, y, loss = "ls")
predict(m1, newx = X)
predict(m1, s=3, newx = X)
predict(m1, s=1:3, newx = X)
```
